In [34]:
import pandas as pd
import numpy as np
import pickle as pkl
import torch

In [2]:
dataset_folder = "../dataset/"
word2vec_emb_file = dataset_folder + "Word2VecAverageArray.npy"
cnn_file = dataset_folder + "googleNet_rep.npy"

In [10]:
df = pd.read_csv("../dataset/books_with_genres.csv")
df.head()

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,...,"history, historical fiction, biography",fiction,"fantasy, paranormal","mystery, thriller, crime",poetry,romance,non-fiction,children,young-adult,"comics, graphic"
0,NaN,7,['189911'],US,eng,"[{'count': '58', 'name': 'to-read'}, {'count':...",B00071IKUY,False,4.03,NaN,...,0,1,1,1,1,0,0,0,0,0
1,0842379428,566,[],US,eng,"[{'count': '6393', 'name': 'to-read'}, {'count...",NaN,False,4.26,B000FCKCJC,...,0,0,0,0,0,0,1,0,0,0
2,0590417010,193,[],US,eng,"[{'count': '450', 'name': 'to-read'}, {'count'...",NaN,False,4.43,B017RORXNI,...,0,1,0,0,0,0,1,1,1,0
3,1400041694,44,[],US,en-US,"[{'count': '362', 'name': 'to-read'}, {'count'...",NaN,False,3.75,B002OTKEP6,...,1,1,0,0,0,0,1,0,0,0
4,NaN,1,[],US,eng,"[{'count': '8', 'name': 'to-read'}, {'count': ...",NaN,False,3.83,NaN,...,0,0,0,0,1,0,0,0,0,0

In [3]:
word2vec_emb = np.load(word2vec_emb_file)
word2vec_emb.shape

(5000, 100)

In [4]:
cnn_emb = np.load(cnn_file, allow_pickle=True)

In [9]:
cnn_emb.shape

(5000,)

In [12]:
df[[f"word2vec_emb{i}" for i in range(0, 100)]] = word2vec_emb
df.head()

/home/a/ajayago/.conda/envs/cs5260/lib/python3.7/site-packages/pandas/core/frame.py:3678: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  self[col] = igetitem(value, i)

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,...,word2vec_emb90,word2vec_emb91,word2vec_emb92,word2vec_emb93,word2vec_emb94,word2vec_emb95,word2vec_emb96,word2vec_emb97,word2vec_emb98,word2vec_emb99
0,NaN,7,['189911'],US,eng,"[{'count': '58', 'name': 'to-read'}, {'count':...",B00071IKUY,False,4.03,NaN,...,0.413907,-0.446276,-0.315774,0.693903,-0.241090,0.656830,0.129635,-0.400377,-0.174691,0.222009
1,0842379428,566,[],US,eng,"[{'count': '6393', 'name': 'to-read'}, {'count...",NaN,False,4.26,B000FCKCJC,...,0.645536,-0.609577,-0.605080,0.876479,-0.893189,0.652011,0.485261,-0.276047,0.052712,0.560401
2,0590417010,193,[],US,eng,"[{'count': '450', 'name': 'to-read'}, {'count'...",NaN,False,4.43,B017RORXNI,...,0.575870,-0.566132,-0.509746,0.785629,-0.678030,0.601758,0.300905,-0.297517,0.023764,0.414339
3,1400041694,44,[],US,en-US,"[{'count': '362', 'name': 'to-read'}, {'count'...",NaN,False,3.75,B002OTKEP6,...,0.480756,-0.479491,-0.469640,0.638183,-0.594718,0.456526,0.262113,-0.256089,0.019272,0.340762
4,NaN,1,[],US,eng,"[{'count': '8', 'name': 'to-read'}, {'count': ...",NaN,False,3.83,NaN,...,0.448217,-0.463576,-0.369393,0.772295,-0.317327,0.735365,0.140419,-0.492817,-0.014760,0.229503

In [25]:
cnn_emb_dict = {}
for c in cnn_emb:
    cnn_emb_dict[list(c.keys())[0]] = c[list(c.keys())[0]]

In [29]:
df["cnn_emb"] = df["book_id"].astype('str').apply(lambda x: cnn_emb_dict[x])
df.head()

/home/a/ajayago/.conda/envs/cs5260/lib/python3.7/site-packages/ipykernel_launcher.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  """Entry point for launching an IPython kernel.

,isbn,text_reviews_count,series,country_code,language_code,popular_shelves,asin,is_ebook,average_rating,kindle_asin,...,word2vec_emb91,word2vec_emb92,word2vec_emb93,word2vec_emb94,word2vec_emb95,word2vec_emb96,word2vec_emb97,word2vec_emb98,word2vec_emb99,cnn_emb
0,NaN,7,['189911'],US,eng,"[{'count': '58', 'name': 'to-read'}, {'count':...",B00071IKUY,False,4.03,NaN,...,-0.446276,-0.315774,0.693903,-0.241090,0.656830,0.129635,-0.400377,-0.174691,0.222009,"[[tensor(0.3346), tensor(0.8039), tensor(-1.53..."
1,0842379428,566,[],US,eng,"[{'count': '6393', 'name': 'to-read'}, {'count...",NaN,False,4.26,B000FCKCJC,...,-0.609577,-0.605080,0.876479,-0.893189,0.652011,0.485261,-0.276047,0.052712,0.560401,"[[tensor(0.9929), tensor(0.0823), tensor(-1.19..."
2,0590417010,193,[],US,eng,"[{'count': '450', 'name': 'to-read'}, {'count'...",NaN,False,4.43,B017RORXNI,...,-0.566132,-0.509746,0.785629,-0.678030,0.601758,0.300905,-0.297517,0.023764,0.414339,"[[tensor(0.8658), tensor(0.7940), tensor(-0.29..."
3,1400041694,44,[],US,en-US,"[{'count': '362', 'name': 'to-read'}, {'count'...",NaN,False,3.75,B002OTKEP6,...,-0.479491,-0.469640,0.638183,-0.594718,0.456526,0.262113,-0.256089,0.019272,0.340762,"[[tensor(0.2560), tensor(-1.1774), tensor(-0.9..."
4,NaN,1,[],US,eng,"[{'count': '8', 'name': 'to-read'}, {'count': ...",NaN,False,3.83,NaN,...,-0.463576,-0.369393,0.772295,-0.317327,0.735365,0.140419,-0.492817,-0.014760,0.229503,"[[tensor(-0.0218), tensor(-0.0105), tensor(-1...."

In [59]:
word2vec_tensor = torch.Tensor(df[[f"word2vec_emb{i}" for i in range(0, 100)]].values)
word2vec_tensor.size()

torch.Size([5000, 100])

In [52]:
x = np.zeros((5000, 1000))
for i in range(len(df["cnn_emb"])):
    x[i] = df["cnn_emb"][i].numpy()

In [61]:
cnn_emb_tensor = torch.Tensor(x)
cnn_emb_tensor.size()

torch.Size([5000, 1000])

In [62]:
torch.save(word2vec_tensor, "../dataset/word2vec_emb_tensor.pkl")

In [65]:
torch.save(cnn_emb_tensor, "../dataset/cnn_emb_tensor.pkl")